// Code generated by cmd/gen-types; DO NOT EDIT.

export interface AccessControl {
  enabled: boolean;
  provider: string;
  session_ttl_minutes: number;
}

export interface AccessControlUpdate {
  enabled?: boolean;
  provider?: string;
  session_ttl_minutes?: number;
}

export interface BranchSuggest {
  target?: string;
}

export interface BranchSuggestUpdate {
  target?: string;
}

export interface ConfigResponse {
  workspace_path: string;
  source_code_manager: string;
  repos: Repo[];
  run_targets: RunTarget[];
  quick_launch: QuickLaunch[];
  external_diff_commands?: ExternalDiffCommand[];
  external_diff_cleanup_after_ms?: number;
  variants?: Variant[];
  terminal: Terminal;
  nudgenik: Nudgenik;
  branch_suggest: BranchSuggest;
  sessions: Sessions;
  xterm: Xterm;
  network: Network;
  access_control: AccessControl;
  needs_restart: boolean;
}

export interface ConfigUpdateRequest {
  workspace_path?: string;
  source_code_manager?: string;
  repos?: Repo[];
  run_targets?: RunTarget[];
  quick_launch?: QuickLaunch[];
  external_diff_commands?: ExternalDiffCommand[];
  external_diff_cleanup_after_ms?: number;
  variants?: Variant[];
  nudgenik?: NudgenikUpdate;
  branch_suggest?: BranchSuggestUpdate;
  terminal?: TerminalUpdate;
  sessions?: SessionsUpdate;
  xterm?: XtermUpdate;
  network?: NetworkUpdate;
  access_control?: AccessControlUpdate;
}

export interface ExternalDiffCommand {
  name: string;
  command: string;
}

export interface Network {
  bind_address: string;
  port: number;
  public_base_url: string;
  tls?: TLS;
}

export interface NetworkUpdate {
  bind_address?: string;
  port?: number;
  public_base_url?: string;
  tls?: TLSUpdate;
}

export interface Nudgenik {
  target?: string;
  viewed_buffer_ms: number;
  seen_interval_ms: number;
}

export interface NudgenikUpdate {
  target?: string;
  viewed_buffer_ms?: number;
  seen_interval_ms?: number;
}

export interface QuickLaunch {
  name: string;
  target: string;
  prompt?: string;
}

export interface Repo {
  name: string;
  url: string;
}

export interface RunTarget {
  name: string;
  type: string;
  command: string;
  source?: string;
}

export interface Sessions {
  dashboard_poll_interval_ms: number;
  git_status_poll_interval_ms: number;
  git_clone_timeout_ms: number;
  git_status_timeout_ms: number;
}

export interface SessionsUpdate {
  dashboard_poll_interval_ms?: number;
  git_status_poll_interval_ms?: number;
  git_clone_timeout_ms?: number;
  git_status_timeout_ms?: number;
}

export interface TLS {
  cert_path: string;
  key_path: string;
}

export interface TLSUpdate {
  cert_path?: string;
  key_path?: string;
}

export interface Terminal {
  width: number;
  height: number;
  seed_lines: number;
  bootstrap_lines: number;
}

export interface TerminalUpdate {
  width?: number;
  height?: number;
  seed_lines?: number;
  bootstrap_lines?: number;
}

export interface Variant {
  name: string;
  enabled?: boolean;
  env?: Record<string, string>;
}

export interface Xterm {
  mtime_poll_interval_ms: number;
  query_timeout_ms: number;
  operation_timeout_ms: number;
  max_log_size_mb?: number;
  rotated_log_size_mb?: number;
}

export interface XtermUpdate {
  mtime_poll_interval_ms?: number;
  query_timeout_ms?: number;
  operation_timeout_ms?: number;
  max_log_size_mb?: number;
  rotated_log_size_mb?: number;
}

