// Code generated by cmd/gen-types; DO NOT EDIT.

export interface AccessControl {
  enabled: boolean;
  provider: string;
  session_ttl_minutes: number;
}

export interface AccessControlUpdate {
  enabled?: boolean;
  provider?: string;
  session_ttl_minutes?: number;
}

export interface BranchSuggest {
  target?: string;
}

export interface BranchSuggestUpdate {
  target?: string;
}

export interface ConfigResponse {
  workspace_path: string;
  source_code_management: string;
  repos: RepoWithConfig[];
  run_targets: RunTarget[];
  quick_launch: QuickLaunch[];
  external_diff_commands?: ExternalDiffCommand[];
  external_diff_cleanup_after_ms?: number;
  models: Model[];
  terminal: Terminal;
  nudgenik: Nudgenik;
  branch_suggest: BranchSuggest;
  conflict_resolve: ConflictResolve;
  sessions: Sessions;
  xterm: Xterm;
  network: Network;
  access_control: AccessControl;
  pr_review: PrReview;
  notifications: Notifications;
  needs_restart: boolean;
}

export interface ConfigUpdateRequest {
  workspace_path?: string;
  source_code_management?: string;
  repos?: Repo[];
  run_targets?: RunTarget[];
  quick_launch?: QuickLaunch[];
  external_diff_commands?: ExternalDiffCommand[];
  external_diff_cleanup_after_ms?: number;
  nudgenik?: NudgenikUpdate;
  branch_suggest?: BranchSuggestUpdate;
  conflict_resolve?: ConflictResolveUpdate;
  terminal?: TerminalUpdate;
  sessions?: SessionsUpdate;
  xterm?: XtermUpdate;
  network?: NetworkUpdate;
  access_control?: AccessControlUpdate;
  pr_review?: PrReviewUpdate;
  notifications?: NotificationsUpdate;
}

export interface ConflictResolve {
  target?: string;
  timeout_ms: number;
}

export interface ConflictResolveUpdate {
  target?: string;
  timeout_ms?: number;
}

export interface ExternalDiffCommand {
  name: string;
  command: string;
}

export interface GitGraphBranch {
  head: string;
  is_main: boolean;
  workspace_ids: string[];
}

export interface GitGraphDirtyState {
  files_changed: number;
  lines_added: number;
  lines_removed: number;
}

export interface GitGraphNode {
  hash: string;
  short_hash: string;
  message: string;
  author: string;
  timestamp: string;
  parents: string[];
  branches: string[];
  is_head: string[];
  workspace_ids: string[];
}

export interface GitGraphResponse {
  repo: string;
  nodes: GitGraphNode[];
  branches: Record<string, GitGraphBranch>;
  dirty_state?: GitGraphDirtyState;
}

export interface Model {
  id: string;
  display_name: string;
  base_tool: string;
  provider: string;
  category: string;
  required_secrets?: string[];
  usage_url?: string;
  configured: boolean;
}

export interface Network {
  bind_address: string;
  port: number;
  public_base_url: string;
  tls?: TLS;
}

export interface NetworkUpdate {
  bind_address?: string;
  port?: number;
  public_base_url?: string;
  tls?: TLSUpdate;
}

export interface Notifications {
  sound_disabled: boolean;
}

export interface NotificationsUpdate {
  sound_disabled?: boolean;
}

export interface Nudgenik {
  target?: string;
  viewed_buffer_ms: number;
  seen_interval_ms: number;
}

export interface NudgenikUpdate {
  target?: string;
  viewed_buffer_ms?: number;
  seen_interval_ms?: number;
}

export interface PRsResponse {
  prs: PullRequest[];
  last_fetched_at?: string;
  error?: string;
}

export interface PrReview {
  target: string;
}

export interface PrReviewUpdate {
  target?: string;
}

export interface PullRequest {
  number: number;
  title: string;
  body: string;
  state: string;
  repo_name: string;
  repo_url: string;
  source_branch: string;
  target_branch: string;
  author: string;
  created_at: string;
  html_url: string;
  fork_owner?: string;
  is_fork: boolean;
}

export interface QuickLaunch {
  name: string;
  command?: string;
  target?: string;
  prompt?: string;
}

export interface Repo {
  name: string;
  url: string;
}

export interface RepoConfig {
  quick_launch?: QuickLaunch[];
}

export interface RepoWithConfig {
  name: string;
  url: string;
  default_branch?: string;
  config?: RepoConfig;
}

export interface RunTarget {
  name: string;
  type: string;
  command: string;
  source?: string;
}

export interface Sessions {
  dashboard_poll_interval_ms: number;
  git_status_poll_interval_ms: number;
  git_clone_timeout_ms: number;
  git_status_timeout_ms: number;
}

export interface SessionsUpdate {
  dashboard_poll_interval_ms?: number;
  git_status_poll_interval_ms?: number;
  git_clone_timeout_ms?: number;
  git_status_timeout_ms?: number;
}

export interface TLS {
  cert_path: string;
  key_path: string;
}

export interface TLSUpdate {
  cert_path?: string;
  key_path?: string;
}

export interface Terminal {
  width: number;
  height: number;
  seed_lines: number;
  bootstrap_lines: number;
}

export interface TerminalUpdate {
  width?: number;
  height?: number;
  seed_lines?: number;
  bootstrap_lines?: number;
}

export interface Xterm {
  mtime_poll_interval_ms: number;
  query_timeout_ms: number;
  operation_timeout_ms: number;
  max_log_size_mb?: number;
  rotated_log_size_mb?: number;
}

export interface XtermUpdate {
  mtime_poll_interval_ms?: number;
  query_timeout_ms?: number;
  operation_timeout_ms?: number;
  max_log_size_mb?: number;
  rotated_log_size_mb?: number;
}

